import { Container } from "@/components/Container";
import { buildMetadata } from "@/lib/seo";

export const metadata = buildMetadata({
  title: "Terms of Use",
  description:
    "Terms of use for SEO Check Tools. Free tools provided as-is; AI outputs can be used for any lawful purpose.",
  path: "terms",
});

export default function TermsPage() {
  return (
    <Container as="main" className="py-12 sm:py-16">
      <article className="mx-auto max-w-2xl prose prose-gray">
        <h1 className="text-3xl font-semibold tracking-tight text-gray-900 sm:text-4xl">
          Terms of Use
        </h1>
        <p className="mt-2 text-sm text-gray-500">Last updated: replace-with-date</p>

        <h2 className="mt-8 text-xl font-semibold text-gray-900">Use of the service</h2>
        <p className="mt-2 text-base text-gray-700 leading-relaxed">
          SEO Check Tools is provided free of charge for personal and commercial
          use. You may use any output generated by our tools for any lawful
          purpose, including commercial projects, without attribution.
        </p>

        <h2 className="mt-8 text-xl font-semibold text-gray-900">Fair use limits</h2>
        <p className="mt-2 text-base text-gray-700 leading-relaxed">
          AI-powered tools have a daily per-IP rate limit to keep the service
          free for everyone. Automated abuse, scraping, or attempts to
          circumvent these limits may result in a temporary or permanent block.
        </p>

        <h2 className="mt-8 text-xl font-semibold text-gray-900">No warranty</h2>
        <p className="mt-2 text-base text-gray-700 leading-relaxed">
          The tools are provided &quot;as is&quot;. AI-generated content may
          contain errors or inaccuracies. You are responsible for reviewing and
          editing any output before publishing or relying on it.
        </p>

        <h2 className="mt-8 text-xl font-semibold text-gray-900">AI output ownership</h2>
        <p className="mt-2 text-base text-gray-700 leading-relaxed">
          AI outputs may not be copyrightable in all jurisdictions. Please
          consult local law for the specifics of your case. We claim no rights
          over content generated for you.
        </p>

        <h2 className="mt-8 text-xl font-semibold text-gray-900">Changes</h2>
        <p className="mt-2 text-base text-gray-700 leading-relaxed">
          These terms may be updated as the service evolves. Material changes
          will be noted on this page.
        </p>
      </article>
    </Container>
  );
}
