import Link from "next/link";
import { ToolLayout } from "@/components/ToolLayout";
import { ChapterGeneratorTool } from "@/components/tools/ChapterGeneratorTool";
import { buildMetadata } from "@/lib/seo";
import { getToolBySlug } from "@/lib/tools-catalog";

const tool = getToolBySlug("youtube-chapter-generator")!;

export const metadata = buildMetadata({
  title: tool.title,
  description: tool.metaDescription,
  path: `tools/${tool.slug}`,
});

const FAQS = [
  {
    q: "What are YouTube's exact requirements for chapters to work?",
    a: "Four rules, all required. First timestamp must be 0:00. At least three chapters total. Each chapter must be at least 10 seconds long. Timestamps must be in strict ascending order. Miss any one and YouTube quietly skips rendering chapters on your video — no error, just nothing happens.",
  },
  {
    q: "Why does my video show chapters anyway when I miss a rule?",
    a: "It probably doesn't — you're likely looking at automatic chapters generated by YouTube's AI. Those use the same UI but are inferred from the video, not from your description. You can disable AI chapters in YouTube Studio if they're showing instead of your manual ones.",
  },
  {
    q: "Does the title length affect anything?",
    a: "No hard limit, but chapter titles get truncated visually in the chapter list around 40-50 characters depending on viewport. Keep them concise — they're navigation labels, not titles.",
  },
  {
    q: "Can I use emojis in chapter titles?",
    a: "Yes. Emojis render fine in the YouTube chapter UI. Some creators use them as visual category markers (🎵 for music sections, 💡 for tips, etc.) — fine for engagement but not a ranking factor.",
  },
  {
    q: "What about chapter thumbnails?",
    a: "YouTube auto-generates a thumbnail for each chapter from the frame at the chapter start time. You can't override this from the description — only from YouTube Studio's chapter editor.",
  },
  {
    q: "Will this work for Shorts?",
    a: "No. YouTube Shorts don't support chapters at all. Chapters only work for long-form videos (typically 1+ minute, though there's no official minimum).",
  },
  {
    q: "Do you save what I paste here?",
    a: "No. Everything is parsed in your browser. The input never leaves your device.",
  },
];

export default function YouTubeChapterGeneratorPage() {
  return (
    <>
      <ToolLayout tool={tool}>
        <ChapterGeneratorTool />
      </ToolLayout>

      <section className="border-t border-gray-100 bg-gray-50/40 py-16">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <h2 className="text-2xl font-semibold tracking-tight text-gray-900">
            About the Chapter Generator
          </h2>
          <p className="mt-4 text-base text-gray-700 leading-relaxed">
            YouTube chapters break a long video into navigable segments that
            show up as clickable markers on the progress bar. They&apos;re a
            free engagement boost — viewers skip to what they want and stay
            longer overall — and they help YouTube&apos;s algorithm understand
            the structure of your content.
          </p>
          <p className="mt-3 text-base text-gray-700 leading-relaxed">
            The catch is that YouTube&apos;s rules for chapters to activate are
            strict and silent. If anything is off, chapters just don&apos;t show.
            This tool parses your timestamped lines, validates them against
            those rules, and tells you exactly what&apos;s wrong if anything
            is.
          </p>

          <h3 className="mt-10 text-lg font-semibold text-gray-900">
            YouTube&apos;s chapter rules
          </h3>
          <ul className="mt-3 space-y-2 text-sm text-gray-700">
            <li>
              <strong>1.</strong> The first chapter must start at{" "}
              <span className="font-mono">0:00</span>
            </li>
            <li>
              <strong>2.</strong> There must be at least{" "}
              <strong>3 chapters</strong> total
            </li>
            <li>
              <strong>3.</strong> Each chapter must be at least{" "}
              <strong>10 seconds</strong> long
            </li>
            <li>
              <strong>4.</strong> Timestamps must be in strict ascending order
            </li>
          </ul>

          <h3 className="mt-10 text-lg font-semibold text-gray-900">
            Supported input formats
          </h3>
          <ul className="mt-3 space-y-2 text-sm text-gray-700">
            <li>
              <span className="font-mono">0:00 Intro</span> — standard format
            </li>
            <li>
              <span className="font-mono">0:00 - Intro</span> — with dash separator
            </li>
            <li>
              <span className="font-mono">0:00 — Intro</span> — with em-dash separator
            </li>
            <li>
              <span className="font-mono">00:00:00 Intro</span> — with hours
            </li>
          </ul>

          <h3 className="mt-12 text-lg font-semibold text-gray-900">
            Frequently asked questions
          </h3>
          <div className="mt-4 divide-y divide-gray-200">
            {FAQS.map(({ q, a }) => (
              <details key={q} className="group py-4">
                <summary className="flex cursor-pointer items-center justify-between text-base font-medium text-gray-900">
                  {q}
                  <span className="ml-4 shrink-0 text-gray-400 transition-transform group-open:rotate-45 text-xl leading-none">
                    +
                  </span>
                </summary>
                <p className="mt-2 text-sm text-gray-600 leading-relaxed">{a}</p>
              </details>
            ))}
          </div>

          <div className="mt-12 rounded-lg border border-gray-200 bg-white p-5">
            <h3 className="text-base font-semibold text-gray-900">Related tools</h3>
            <p className="mt-1 text-sm text-gray-600">
              Pair this with other tools for a complete video description.
            </p>
            <ul className="mt-4 grid gap-2 sm:grid-cols-2">
              <li>
                <Link href="/tools/youtube-description-generator" className="link text-sm">
                  AI Description Generator →
                </Link>
              </li>
              <li>
                <Link href="/tools/youtube-tag-generator" className="link text-sm">
                  AI Tag Generator →
                </Link>
              </li>
              <li>
                <Link href="/tools/youtube-hashtag-generator" className="link text-sm">
                  AI Hashtag Generator →
                </Link>
              </li>
              <li>
                <Link href="/tools" className="link text-sm">
                  All YouTube tools →
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </>
  );
}
